[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.25"
optimizer = true
optimizer-runs = 100_000

[rpc_endpoints]
mainnet = "https://rpc.mevblocker.io/noreverts"
sepolia = "https://ethereum-sepolia.publicnode.com"
gnosis = "https://rpc.gnosischain.com"
